model:
  name: BestNCAA
  type: PRN
  param:
    in_dim: 1024
    hidden_dim: 512
    feat_dim: 256
    app_type: both
    attn_param:
        in_dim: 512 
        hidden_dim: 128
        out_dim: 256 
        sub_param:
          x_in_dim: 512
          y_in_dim: 128
          hidden_dim: 128
          out_dim: 128
batch_size: 3
seed: 3
num_ins: 8
num_worker: 8
log_inter: 1
save_inter: 5
models_path: /home/yukun/PersonRelationNetwork/packages/models
loss_weights:
  ce_loss: 1.0
epoch: 200
opt: {type: sgd, lr: 1.e-3, gamma: 0.5, m: 0.9, wd: 5.e-4, lde: 25}
lambda:
  face: 0
  ctx: 0
  fbg: 0.75
  relat: 1 
max_ckpt_num: 10
dataset: NCAA
percent: 1.0
data:
  path:
    MS: /data/yukun/MS/data/processed(multi).pkl
    NCAA: /data/yukun/NCAA/data/processed(multi).pkl
  mean:
    MS: [0.4335, 0.3931, 0.3729]
    NCAA: [0.4746, 0.4220, 0.3884]
  std:
    MS: [0.2930, 0.2826, 0.2814]
    NCAA: [0.3179, 0.2773, 0.2375]
  data_augment: 
    is_use: [True, True, True, True]
